### ISSUE TITLE
$? value when ctrl on prompt

### ISSUE THREAD

**Issue by tmeyer24** [Alikae/42sh#76]
Currently 0 but should be 130

**Comment by tmeyer24** [comment]
Est-ce que je dois set last_cmd_result à 130 moi-même au moment où je capte le CTRL-C ?

**Comment by Alikae** [comment]
Je suppose, je savais pas ca

**Comment by Alikae** [comment]
Du coup ouais

**Comment by tmeyer24** [comment]
En fait c'est plus chiant que ça, bash renvoie 130 quand t'envoie un SIGINT peut importe à qui, que ce soit sur le prompt ou genre pendant un ls -R de la racine que tu kill. Actuellement on renvoie 0

**Comment by tmeyer24** [comment]
du coup sauf pendant le prompt vu que t'as changé ça

**Comment by tmeyer24** [comment]
125 + nb signal de retour

**Comment by tmeyer24** [comment]
Mm pb pour CTRL-\\, la valeur cette fois c'est 131
