### ISSUE TITLE
cd

### ISSUE THREAD

**Issue by tcillard** [Alikae/42sh#97]
cd -P /tmp
can't access private/tmp
miss the / at the front

pwd=/Users/tcillard
ln -s / a
cd a/Users
pwd=/Users/tcillard/a/Users
cd ../..
pwd=/ but we should be in /Users/tcillard

**Comment by tmeyer24** [comment]
First problem solved

**Comment by tmeyer24** [comment]
Pour la deuxieme, on doit revoir le process. On a la bonne variable PWD, mais chdir set le path au mauvais directory. Donc, dans le cas ou le path est relatif, (ie qu'il commence pas par un /), je construis le path avec les liens, tu le génères en fonction du précédent, et si chdir marche, tu set PWD et OLDPWD
